micronaut:
  application:
    name: desafioPix
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/desafio-pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    chave-pix:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5

api-contas-itau-url: 'http://localhost:9091'